### ISSUE TITLE
Update datasets after ADTTE/ADRS refactoring

### ISSUE THREAD

**Issue by edelarua** [insightsengineering/scda.2022#119]
To do after the following are resolved:

- [x] https://github.com/insightsengineering/random.cdisc.data/issues/254
- [ ] https://github.com/insightsengineering/random.cdisc.data/issues/271
- [ ] https://github.com/insightsengineering/random.cdisc.data/issues/234

**Comment by shajoezhu** [comment]
close the issue, as the package will be retired
