### ISSUE TITLE
The synthetic CDISC data released during 2022

### ISSUE THREAD

**Issue by botsp** [insightsengineering/scda.2022#137]
### What is your question?

It seems this package only contains ADAM datasets, right? No sdtm datasets.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Melkiades** [comment]
I think so. is it right @shajoezhu? We are anyway moving out from this cache package to use directly `random.cdisc.data` that has all the generation functions and details

**Comment by botsp** [comment]
Thanks for the introduction. What's the main difference between these two packages of data?

By the way, I also noticed the "OAK" project, as it mentioned the "raw.synthetic.data", it's still under development, right? I found no related materials about this package.

https://www.cdisc.org/sites/default/files/2023-02/SDTM_Automation_OAK_CDISC_COSA.pdf

**Comment by shajoezhu** [comment]
this one only contains adam data. you might also be interested in 
https://github.com/pharmaverse/pharmaverseadam

if you need sdtm data, take a look at 
https://github.com/pharmaverse/pharmaversesdtm

if you looking for the program to create data, there is also 
there is also https://github.com/openpharma/DataFakeR
 and https://github.com/insightsengineering/random.cdisc.data

**Comment by botsp** [comment]
Thank you Joe. I just start to learn the R usage in CDISC area and impressed by such great work from your team. 
Looking forward to the success of {OAK}.
