### ISSUE TITLE
Init `gh_pages`

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/scda.2022#144]
There are some discussions about retirement but until this happen can we initiate `gh_pages`? Currently, a few workflows fail because of this.
![image](https://github.com/insightsengineering/scda.2022/assets/12943682/69e92c31-a08b-4b7c-9996-88cc3cd10bb0)

Also the main Docs workflow (ran manually) fails:
![image](https://github.com/insightsengineering/scda.2022/assets/12943682/9f96e674-ea12-4478-9f58-5b34ab0f0b79)

**Comment by pawelru** [comment]
@cicdguy could you please help on this? Is it as easy as just creating a new branch or there is something more to be done?

**Comment by pawelru** [comment]
ok thanks - let me do this

**Comment by shajoezhu** [comment]
closing this issue because of https://github.com/insightsengineering/scda.2022/issues/142
