### ISSUE TITLE
Handle example data for CRAN

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/scda.2022#71]
- Do we want the package to be called scda.2022 or something else
- The size of the package gets big quickly which makes `R CND check --as-cran` not happy - though see https://github.com/insightsengineering/scda/issues/98

![image](https://user-images.githubusercontent.com/15201933/189355006-6929cc07-4e81-4d3d-a277-498e2773aeb4.png)

- Users just want the example data they have to work with the example code, they are not interested in archives of old data - that's only useful for test cases
- It may make sense for the data to end up in scda itself which would simplify some things...

Also consider https://github.com/insightsengineering/scda.2021/issues/91

**Comment by shajoezhu** [comment]
I thought cran does not take data packages? Please correct me if I was wrong

**Comment by nikolas-burkoff** [comment]
hmm - if it doesn't then we can't submit any package which uses the data package (even in suggests)?

**Comment by shajoezhu** [comment]
Hi @nikolas-burkoff , yea, I think we will need to discuss about the releasing plan. From a recent conversation, i think we can push to bioconductor, which is ok for the other packages have scda to be a suggested package.

**Comment by shajoezhu** [comment]
I think we can close this issue now. As scda* families are now being decoupled from tern, we will not release scda to cran
